### ISSUE TITLE
SWPP Bug report - 중복 회원 가입 관련

### ISSUE THREAD

**Issue by sharkmir1** [swsnu/swpp2019-team3#162]
**Describe the bug**
test@test.com으로 회원가입하려하면 이메일이 이미 존재한다고 되어있는데, test@test.com으로 로그인하려하면 존재하지 않는 이메일이라고 뜹니다.

**Comment by davin111** [comment]
@sharkmir1 해당 이메일을 가진 계정은 존재하지 않아서 방금 제가 직접 해당 이메일로 가입해보았는데, 문제가 없는 것 같습니다. 혹시 다른 팀 서비스에 대한 이슈와 헷갈리신 것일까요?
