### ISSUE TITLE
[Feature request] (minor) Button 용어 관련

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team3#163]
**Is your feature request related to a problem? Please describe.**
Add this paper to collections 팝업이 떴을 때 update가 눌러야 하는 버튼인 듯 한데, update 버튼이 뭘 의미하는지 모르겠어요! 다른 단어로 설명되면 좋을 것 같습니다!

**Additional context**
<img width="1440" alt="Screen Shot 2019-12-05 at 7 01 26 PM" src="https://user-images.githubusercontent.com/13305988/70225125-c588e000-1791-11ea-8c56-f759d7914d2e.png">

**Comment by njsh4261** [comment]
좋은 지적 감사합니다. 더 직관적인 단어로 수정하겠습니다.
