### ISSUE TITLE
Create collection 후 업데이트

### ISSUE THREAD

**Issue by dreamsh19** [swsnu/swpp2019-team3#164]
Create new collection에서 create버튼을 눌러
create하면 바로 collection 모음에 업데이트 되지 않고
새로고침하거나 collection 버튼을 다시 눌러야 업데이트 되어
바로 업데이트 되도록 수정하면 좀 더 편하게 사용할 수 있을 것 같습니다.

**Comment by dreamsh19** [comment]
그리고 History에 모든 변경사항이 반영되지 않는 것 같습니다!

**Comment by ttoru96** [comment]
> Create new collection에서 create버튼을 눌러
> create하면 바로 collection 모음에 업데이트 되지 않고
> 새로고침하거나 collection 버튼을 다시 눌러야 업데이트 되어
> 바로 업데이트 되도록 수정하면 좀 더 편하게 사용할 수 있을 것 같습니다.

동일한 문제가 발생합니다

환경: 
OS: mac sierra
브라우저: chrome

**Comment by davin111** [comment]
앗 감사합니다, 해당 문제를 이전에 봤었는데 최근에 업데이트하면서 문제가 생긴 것 같습니다. 물론 새로고침하면 확인할 수 있기는 합니다. 감사합니다!

@dreamsh19 History 관련된 것은 어떤 말씀이신지 조금도 구체적으로 얘기해주실 수 있을까요?
