### ISSUE TITLE
confirm 이후 아무일도 일어나지 않습니다

### ISSUE THREAD

**Issue by iamsungyeonjoo** [swsnu/swpp2019-team3#165]
![image](https://user-images.githubusercontent.com/33143827/70225340-2d3f2b00-1792-11ea-9a72-c9ea410b239e.png)
여기서 confirm 누르는데 아무일도 안 일어납니다.

**Comment by iamsungyeonjoo** [comment]
아마도 5개 이하로 골라서 그런 것 같은데, warning message를 띄워주시면 감사하겠습니다.

**Comment by abcthing** [comment]
넵! 감사합니다

**Comment by davin111** [comment]
We decided not to reflect this suggestion. The deactivated 'Confirm' button has a different color, so users can know it intuitively.
