### ISSUE TITLE
[Bug report] user 간 collection 충돌?

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team3#166]
**Describe the bug**
제가 추가한 적 없는 collection이 생긴 것 같은데, collection이 user별로 unique했으면 좋겠습니다!

**Screenshots**
<img width="1440" alt="Screen Shot 2019-12-05 at 7 05 52 PM" src="https://user-images.githubusercontent.com/13305988/70225399-4ea01700-1792-11ea-9d90-76ee2b5aafa4.png">
(여기서 qqqqq는 제가 추가한 collection이 아닙니다)

**Comment by kosumin** [comment]
다른 분이 콜렉션에 초대하신 것 같아요!

**Comment by davin111** [comment]
Collection 초대를 받았을 때, 수락하는 과정을 구현해야할 것 같습니다. 혼란을 드려 죄송합니다.
