### ISSUE TITLE
[버그 리포트?] 저도 모르는 콜렉션이 추가됬어요

### ISSUE THREAD

**Issue by vionicbest** [swsnu/swpp2019-team3#167]
**Describe the bug**
![image](https://user-images.githubusercontent.com/38846024/70225452-6a0b2200-1792-11ea-8bf0-3954b67a0c73.png)
위의 908909가 추가됬는데 원래 그런건가요?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by njsh4261** [comment]
버그가 아니라, 저희가 현재 새로 가입하신 분들에 대해서 collection에 초대하였습니다. 그래서 collection list에 추가하지 않은 collection이 보이셨을 겁니다. 차후 collection에 초대되었을 때 수락 기능을 넣는 것을 고려하고 있습니다.

**Comment by davin111** [comment]
#167 issue와 동일한 상황에 대한 내용이므로 닫도록 하겠습니다! 여기서도 언급하고 있듯 '수락' 기능을 적극적으로 고려하겠습니다. 감사합니다. :)
