### ISSUE TITLE
Heart Icon에 대해

### ISSUE THREAD

**Issue by peterhyun** [swsnu/swpp2019-team3#168]
버그는 아닌데, 하트를 누르기 전에도 빨간 테두리가 있는 게 마음에 걸립니다... 인스타그램처럼 클릭하기 전에는 그냥 쌩 흰색이다가, 누르면 하트가 빨강색으로 채워지는 것은 어떨까요?

**Comment by njsh4261** [comment]
디자인 관해서는 포스터 세션 이전까지 작업 중에 있습니다. 의견 감사합니다!
