### ISSUE TITLE
태그 검색

### ISSUE THREAD

**Issue by aeri206** [swsnu/swpp2019-team3#169]
**Describe the bug**
Paper의 tag를 눌렀을때 어떤 결과가 나오는지 모르겠습니다 !
해시태그와 비슷한 기능으로 추측되는데 클릭시 태그가 없는 다른 페이퍼도 나오는것 같습니다

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kosumin** [comment]
tag를 클릭해주시면 해당 tag를 검색어로 하여 검색 기능이 구현됩니다! 그래서 그런 tag가 없는 논문도 나오는 것 같아요. 감사합니다!

**Comment by davin111** [comment]
답변이 되었으므로 이 이슈는 닫도록 하겠습니다. 질문 감사합니다! keyword(tag)에 관련해서는 앞으로 여러가지 방향으로 개선을 시도해보겠습니다.
