### ISSUE TITLE
프로필 이미지를 못 바꿔요

### ISSUE THREAD

**Issue by uyw4687** [swsnu/swpp2019-team3#170]
**Is your feature request related to a problem? Please describe.**
프로필 이미지를 못 바꿔요.

**Describe the solution you'd like**
프로필 이미지 바꾸고 싶어요.

**Describe alternatives you've considered**
고를 수 있으면 되겠어요.

**Additional context**
그럼 좋을 것 같아요.

**Comment by abcthing** [comment]
프로필 이미지를 고를 수 있도록 작업할 예정입니다. 피드백 감사합니다.
