### ISSUE TITLE
저의 프로필의 default 사진이 고양이네요

### ISSUE THREAD

**Issue by iamsungyeonjoo** [swsnu/swpp2019-team3#171]
![image](https://user-images.githubusercontent.com/33143827/70225486-798a6b00-1792-11ea-8f3c-b1f538addc79.png)
너무 귀여운 고양이라 좋지만, 자신의 사진을 바꿀 수 있는 기능이 추가되면 좋을 것 같습니다. 
이에 더해 follower가 2명인데 언제 2명으로 늘었는지 몰랐습니다.
알람 기능이 있는 것 같긴 한데 새로운 알림이 있으면 페북처럼 1이 뜨는 것 처럼 알려줬으면 좋겠스비다.

**Comment by abcthing** [comment]
프로필 사진을 바꿀 수 있는 기능을 작업할 예정입니다! 그리고 현재 notification(new)에 'new' 표시가 새로운 노티가 존재한다는 표시입니다. 하지만 더 직관적으로 보일 수 있도록 작업하겠습니다. 의견 감사합니다.

**Comment by njsh4261** [comment]
follower가 늘어난 건 저희가 저희 팀 test 중에 새로 가입하신 분들에게 notification 기능을 보여드리기 위해서 follow를 했습니다.

**Comment by davin111** [comment]
프로필 이미지 변경에 관해서는 앞선 issue인 #170 에서도 지적된 부분인데, 어서 작업하도록 하겠습니다. 감사합니다.
