### ISSUE TITLE
[Feature Request] (minor) Search results 수 표기 

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team3#172]
**Is your feature request related to a problem? Please describe.**
search를 하면 load more를 누를 때마다 검색창 상단의 count가 업데이트되는데, 오히려 검색결과에 대한 갯수 예측이 어려워지는 것 같습니다. 이 count를 없애도 되지 않을까요?

**Additional context**
<img width="1440" alt="Screen Shot 2019-12-05 at 7 08 08 PM" src="https://user-images.githubusercontent.com/13305988/70225567-9d4db100-1792-11ea-8d67-725ebe67afbd.png">

**Comment by abcthing** [comment]
참고해서 작업하도록 하겠습니다. 의견 감사드려요!
