### ISSUE TITLE
리뷰

### ISSUE THREAD

**Issue by HaeTheong** [swsnu/swpp2019-team3#173]
1. http://www.papersfeed.online/asdf와 같이 잘못된 주소 입력시 리다이렉션이 되면 좋을 것 같아요
2. collection create 시 새로고침이 필요하네요
3. 자신에게 하트가 가능한데 의도하신 바가 맞나요?
4. main에 아무 것도 안뜨는데 뭔가 다른 설정이 필요한 건지 버그인지 모르겠네요

**Comment by davin111** [comment]
@HaeTheong issue 감사합니다. 혹시 Main에서 아무것도 뜨지 않는 상황이 어떻게 접근하셨을 때 발생했는지 조금 더 구체적으로 알려주실 수 있을까요?

**Comment by abcthing** [comment]
1. 넵 의견 감사합니다!
