### ISSUE TITLE
Collection 삭제 관련

### ISSUE THREAD

**Issue by dreammerkr** [swsnu/swpp2019-team3#174]
Collection에 초대 받거나 만든뒤 권한을 이양하게되면 collection은 제거할 수 없습니다.

**Comment by davin111** [comment]
맞습니다, #121 issue에서 언급하고 있는 문제입니다. 어서 해당 기능 추가하도록 하겠습니다.

**Comment by davin111** [comment]
#121 의 issue와 중복되므로, 이 이슈는 닫도록 하겠습니다. 감사합니다!
