### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by 1207koo** [swsnu/swpp2019-team3#175]
1. 우선 콘솔 창에 [Middleware] Next State Object 같은 것이 계속 뜸
2. init 창에서 view more 버튼을 열심히 누르면 같은 체크박스가 중복되어서 쌓임
3. 자기 자신의 reply에 좋아요를 누를 수 있음
4. 좋아요 수가 100이 넘으면 하트가 안 보임
5. 정확한 조건은 모르겠지만 일단 reply를 달고 수정하고 좋아요를 누르면 좋아요 수가 n에서 0이 되었다가 n+1이 됨. 자신의 reply에 무한한 수의 좋아요 달기 가능

**Comment by kosumin** [comment]
자세하게 살펴봐주셔서 정말 감사합니다ㅎㅎ
1번. 이 부분은 개발 과정 중인데 해결할 수 있도록 하겠습니다.
2번. 혹시 2번의 상황에 대해 조금 더 자세하게 들을 수 있을까요? 저의 경우에는 제대로 작동을 해서요ㅠㅠ
3번. 이 부분은 의도한 것인데 관련해서 논의를 해보도록 하겠습니다.
4번. UI 부분도 개선할 수 있도록 하겠습니다.
5번. 이 부분도 개선하도록 하겠습니다. 감사합니다!!

**Comment by davin111** [comment]
@1207koo 다양한 경우를 테스트해보아주셔서 감사합니다, 일단 4.에 대해서는, 아마 [이 컬렉션](http://www.papersfeed.online/collection_id=59)에서의 reply에 대해 테스트해보신 것 같은데 우선 동일한 사람이 중복해서 like를 할 수 있었다는 것부터가 문제였던 것 같습니다. 이런 상황이 발생하지 않도록 수정하도록 하겠습니다. 별개로, 디자인적 측면에서 세 자리 수 이상이 되었을 때의 버튼에 대해 고려하도록 하겠습니다. 감사합니다.
