### ISSUE TITLE
Transfer midpresentation-branch To master

### ISSUE THREAD

**Issue by davin111** [swsnu/swpp2019-team3#61]
In recent days, we hastily developed our service in `midpresentation-branch` for mid presentation demo. As a result, there are a lot of codes which need to be modified and refactored and some dummy data should be deleted. Also, many features lack their tests and there are some issues like #59 handled in the appropriate way, not by ad-hoc codes. So we need to split and improve changes in the `midpresentation-branch`, and gradually merge them to `master`.

**Comment by davin111** [comment]
@ktaebum For today, please build with `midpresentation-branch` instead of `master`, if you plan to build and run our project.

**Comment by ktaebum** [comment]
Minor Comments Before Meeting (could be added more)

1. Form submit when press enter
2. You can use backend as `db.sqlite3` when developing and use `mysql` only in actual deployment (similar with `yarn start` & `yarn build`)
3. CSS layout becomes weird when enable chrome developer mode (intended?)
